AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 实例规格，见 https://aws.amazon.com/ec2/instance-types/

  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: Amazon Linux 2 镜像 ID，通常保持默认值即可

  VolumeSize:
    Type: Number
    Default: 64
    MinValue: 16
    Description: 用于保存下载节目的磁盘大小，单位 GB

  PodsyncVersion:
    Type: String
    Default: latest
    Description: 要使用的 Podsync 版本，见 https://github.com/kyangc/podsync/releases

  PodsyncPort:
    Type: Number
    Default: 8080
    MaxValue: 65535
    Description: Podsync 服务端口

  YouTubeApiKey:
    Type: String
    AllowedPattern: '.+' # 必填
    Description: |
      YouTube API 访问使用的 key，见 https://github.com/kyangc/podsync/blob/main/docs/how_to_get_youtube_api_key.md

  VimeoAccessToken:
    Type: String
    AllowedPattern: '.+' # 必填
    Description: |
      Vimeo API 访问使用的 token，见 https://github.com/kyangc/podsync/blob/main/docs/how_to_get_vimeo_token.md

  FeedId:
    Type: String
    Default: 'ID1'
    AllowedPattern: '.+' # 必填
    Description: |
      feed ID；部署后可以通过类似 http://localhost/ID1.xml 的地址访问

  FeedUrl:
    Type: String
    AllowedPattern: '.+'
    Description: |
      Podsync 要托管的 YouTube、Vimeo 或 Bilibili URL，例如 https://www.youtube.com/user/XYZ

  PageSize:
    Type: Number
    Default: 50
    MinValue: 5
    Description: |
      每次更新查询的节目数量

  Format:
    Type: String
    AllowedValues:
      - 'audio'
      - 'video'
    Default: 'video'
    Description: feed 格式，audio 或 video

  Quality:
    Type: String
    AllowedValues:
      - 'high'
      - 'low'
    Default: 'high'
    Description: feed 质量，high 或 low

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: '虚拟机配置'
        Parameters:
          - InstanceType
          - KeyName
          - AmiId
          - VolumeSize
      - Label:
          default: 'Podsync 配置'
        Parameters:
          - PodsyncVersion
          - PodsyncPort
          - YouTubeApiKey
          - VimeoAccessToken
      - Label:
          default: 'Feed 配置'
        Parameters:
          - FeedId
          - FeedUrl
          - PageSize
          - Format
          - Quality

    ParameterLabels:
      InstanceType:
        default: '实例规格'
      AmiId:
        default: 'AMI ID'
      VolumeSize:
        default: '磁盘大小'
      PodsyncVersion:
        default: '版本'
      PodsyncPort:
        default: '服务端口'
      YouTubeApiKey:
        default: 'YouTube API Key'
      VimeoAccessToken:
        default: 'Vimeo Token'
      FeedId:
        default: 'Feed ID'
      FeedUrl:
        default: 'Feed URL'
      PageSize:
        default: '每页数量'

Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${AWS::StackName}"
  Ec2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Count: 1
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref NewKeyPair
      ImageId: !Ref AmiId
      SecurityGroups:
        - !Ref AccessSecurityGroup
      EbsOptimized: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref VolumeSize
      IamInstanceProfile: !Ref SsmInstanceProfile
      Tags:
        - Key: 'Name'
          Value: !Sub "${AWS::StackName}"
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          set -ex
          trap '/opt/aws/bin/cfn-signal --exit-code 1 --resource Ec2Instance --region ${AWS::Region} --stack ${AWS::StackName}' ERR

          # 安装 Docker
          yum update -y
          amazon-linux-extras install docker
          systemctl start docker
          usermod -a -G docker ec2-user

          export publichost=$(ec2-metadata --public-hostname | cut -d ' ' -f2)
          # 创建配置文件
          mkdir -p /home/ec2-user/podsync/data
          tee /home/ec2-user/podsync/config.toml <<EOF
          [server]
          port = ${PodsyncPort}
          hostname = "http://$publichost:${PodsyncPort}"
          
          [storage]
            [storage.local]
            data_dir = "/home/ec2-user/podsync/data"

          [tokens]
          youtube = "${YouTubeApiKey}"
          vimeo = "${VimeoAccessToken}"

          [feeds]
            [feeds.${FeedId}]
            url = "${FeedUrl}"
            page_size = ${PageSize}
            quality = "${Quality}"
            format = "${Format}"
          EOF

          # 拉取本 fork 镜像并运行
          docker pull ghcr.io/kyangc/podsync:${PodsyncVersion}
          docker run -d \
            -p ${PodsyncPort}:${PodsyncPort} \
            -v /home/ec2-user/podsync/data:/app/data \
            -v /home/ec2-user/podsync/config.toml:/app/config.toml \
            --restart always \
            ghcr.io/kyangc/podsync:${PodsyncVersion}

          # 通知 CloudFormation 初始化成功
          /opt/aws/bin/cfn-signal --exit-code 0 --resource Ec2Instance --region ${AWS::Region} --stack ${AWS::StackName}

  # 配置带 SSM 权限的实例 profile，便于通过 SSM console 连接 EC2。
  SsmIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

  SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${AWS::StackName}"
      Roles:
        - !Ref SsmIamRole

  # 限制 SSH 和 Podsync 服务访问。
  AccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Podsync CLI 安全组：${AWS::StackName}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref PodsyncPort
          ToPort: !Ref PodsyncPort
          CidrIp: 0.0.0.0/0
          Description: 访问 Podsync 服务
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH 访问 EC2

Outputs:
  PodsyncUrl:
    Description: 'Feed URL 地址'
    Value: !Sub "http://${Ec2Instance.PublicDnsName}:${PodsyncPort}/${FeedId}.xml/"
